# Generated by Django 4.2.7 on 2024-01-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_customuser_fullname_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='publicId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
