# Generated by Django 4.2.7 on 2024-01-06 21:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_image_customuser_publicid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='publicId',
        ),
        migrations.AddField(
            model_name='customuser',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
